### ISSUE TITLE
Ability to add multiple outputs

### ISSUE THREAD

**Issue by ariselseng** [olaferlandsen/ffmpeg-php-class#10]
It would be nice to have multiple outputs.
In ffmpeg it is possible to do something like this:
```shell
$ ffmpeg -y  -i input.mov -c:v copy -an  -segment_time 30 -f segment segments/output-%03d.mov \
-vn -acodec aac -b:a 320k audio/output.m4a


What I am trying to accomplish is to generate segments of 30 seconds without audio, and one full length clip with only audio.

**Comment by olaferlandsen** [comment]
Well, for now it is not possible. You're welcome to send pull request 😄

**Comment by newtecnerd13** [comment]
Does this open a door for a security threat?

**Comment by olaferlandsen** [comment]
@newtecnerd13 this depends of you code. This class is only a wrapper for FFmpeg ;)
