### ISSUE TITLE
`ZLIB_1.2.9' not found

### ISSUE THREAD

**Issue by azaddeveloper** [olaferlandsen/ffmpeg-php-class#11]
I am getting this error.
ffmpeg: /opt/lampp/lib/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)

I am using PHP 7.2 and ubuntu 18.04

**Comment by olaferlandsen** [comment]
This is a FFMPEG error.

**Comment by azaddeveloper** [comment]
I don't know what reson this error occure,please suggest what i will do here.

**Comment by olaferlandsen** [comment]
@azaddeveloper https://ubuntuforums.org/showthread.php?t=2375927
