### ISSUE TITLE
File converts zero kb.

### ISSUE THREAD

**Issue by shahbaz-gaxon** [olaferlandsen/ffmpeg-php-class#6]
File converts zero kb.

How to solve this problem.

my code is following..

require '../src/FFmpeg.php';
$FFmpeg = new FFmpeg();
$FFmpeg->input( 'original.mp4' )->output( 'new.flv' )->ready();

**Comment by olaferlandsen** [comment]
please give me u full ffmpeg version like this `ffmpeg -v`

**Comment by ntaloventi** [comment]
yes.. same like me..
file create with zero kb

ffmpeg version N-79139-gde1a0d4 Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libfreetype --enable-gnutls --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvidstab
libavutil      55. 19.100 / 55. 19.100
libavcodec     57. 30.100 / 57. 30.100
libavformat    57. 29.101 / 57. 29.101
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 40.102 /  6. 40.102
libavresample   3.  0.  0 /  3.  0.  0
libswscale      4.  0.100 /  4.  0.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100

thanks...

**Comment by olaferlandsen** [comment]
Please, read [this answer](http://stackoverflow.com/a/10855855), [this answer](http://stackoverflow.com/a/1094420) on StackOverflow, and read [this post](http://jamestombs.co.uk/2008-07-18/converting-video-avi-mov-mpg-mp4-to-flv-using-ffmpeg/531) on James Tombs Blog's.


**Try width this:**

```php
$FFmpeg = new FFmpeg();
// Set input file
$FFmpeg->input( 'original.mp4' );

$FFmpeg->set('c:v', 'libx264');
$FFmpeg->set('presets', 'ultrafast');

// Set audio rate
$FFmpeg->audioSamplingFrequency('22050');

// set output file with FORCE flv format
$FFmpeg->output( 'new.flv' , 'flv');
$FFmpeg->ready();
```
