### ISSUE TITLE
-y flag should be removed

### ISSUE THREAD

**Issue by ssi-anik** [olaferlandsen/ffmpeg-php-class#9]
First of all, thanks for the package. :+1: 
Suppose, I just want to get the duration of a video. I found this code from SO. `ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 input.mp4`. My question is, can I try this?
The answer is: YES. There is a workaround. 
1. ffprobe can be used. But, I have to construct a new object. simply returning `$this` from `ffmpeg` method would be great.
2. the `-y` overwrite flag is always present. I have to unset that. 

Can you just change your code to or should I give you some PR? any help is appreciated. :clap:

**Comment by olaferlandsen** [comment]
Hi @ssi-anik!
I will work in this feature or create a new pull request ;)
> If you send a new PR, I will include in "[thanks to](https://github.com/olaferlandsen/ffmpeg-php-class#thanks-to)"
Thanks!
